worker_processes auto;
events { worker_connections 1024; }
http {
  lua_package_path '/usr/local/openresty/lualib/?.lua;/etc/nginx/lua/?.lua;;';
  resolver 127.0.0.11 ipv6=off;

  server {
    listen 8088;

    location = /healthz { return 200 '{"status":"ok"}'; add_header Content-Type application/json; }
    location = /readyz { proxy_pass http://web-node:8080/readyz; }

    location /api/v1/posts {
      if ($request_method = POST) { access_by_lua_file /etc/nginx/lua/auth.lua; }
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-User-Id $http_x_user_id;
      proxy_pass http://web-node:8080;
    }

    location ~ ^/api/v1/posts/.+/like$ {
      access_by_lua_file /etc/nginx/lua/auth.lua;
      proxy_set_header X-User-Id $http_x_user_id;
      proxy_pass http://web-node:8080;
    }

    location /api/v1/ {
      proxy_pass http://web-node:8080;
    }
  }
}
